server:
  port: 8889

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/dpnevsky/cvsappconfiguration/cvs
          username:
          password:
          default-label: main
          search-paths: "{application}"

